### ISSUE TITLE
Remove closing PHP Tag

### ISSUE THREAD

**Issue by obstschale** [dmhendricks/wordpress-base-plugin#1]
In `wordpress-base-plugin.php` is the closing tag `?>` used. I learnt that this is bad practice and should be avoided.

**Comment by dmhendricks** [comment]
My anal retentivity disallows me from opening a tag without closing it. :/

However, if you can provide sources, I will consider it.

**Comment by obstschale** [comment]
Disclaimer: I'm only talking about PHP-only files. If you use XML, HTML, AND PHP in a file you need to use the closing tag.

Using the php closing tag is optional in PHP and you don't have to use it. I know that is no reason for not using it. But there are benefits omitting the closing tag.

Reduce the risk of PHP errors. The thing is, if you use the closing tag no whitespace may come after that. Otherwise, an Warning: "Cannot modify header information - headers already sent" will show up [1].

In addition, if output buffering is enabled HTTP headers can be set after outputting HTML. Here a quote from StackOverflow:

> Modern versions of PHP set the output_buffering flag in php.ini If output buffering is enabled, you can set HTTP headers and cookies after outputting html because returned code is not sent to the browser immediately.

A lot of people are omitting the closing tag, because it is more convenient. Also WordPress, Drupal, and frameworks like Laravel and Symfony are doing that.

Last but not least, you mentioned PSR-4 in another issue, and I like following standards. PSR-2 [3] states:

> 2.2. Files
> The closing `?>` tag MUST be omitted from files containing only PHP.

Of course, you can use the closing tag, and it is no requirement to follow this practice, but I think it is a good one and so I opened this issue :)

1. [StackOverflow](https://stackoverflow.com/questions/4410704/why-would-one-omit-the-close-tag#4499749)
2. [sitepoint](https://www.sitepoint.com/should-you-close-your-php-code-tags/)
3. [PSR-2](http://www.php-fig.org/psr/psr-2/)

**Comment by dmhendricks** [comment]
Ok, I have done this. Thank you for the recommendation and references.
