### ISSUE TITLE
Remove vendor/ from repo

### ISSUE THREAD

**Issue by obstschale** [dmhendricks/wordpress-base-plugin#2]
- [x] remove `vendor/` from repo

**Comment by obstschale** [comment]
You should not add `vendor/` to your repo. The whole point of composer is, that you don't need to add your dependencies to the repo, but use composer to fetch them. `composer.json` and `composer.lock` are the only files, which should end up in a repo.

**Comment by dmhendricks** [comment]
> The whole point of composer is, that you don't need to add your dependencies to the repo, but use composer to fetch them.

Disagree 100%. If I make a plugin and someone downloads it, they will be disappointed when the dependencies aren't loaded. In my opinion, the whole point of Composer is managing dependencies. Don't believe me? View source on >25% of the web to determine if they are using WordPress and ask if they know what Composer is.

That said and given the intent of this repo, you are largely correct. I suppose that it may be appropriate to remove. After all, if someone doesn't know how to Composer, he/she probably wouldn't find much use for this anyway.

I will probably remove it. I need to update this code anyway. I work >70 hours/week so it has been slow. I will update it, though. I'm currently having an issue with the new version that I haven't resolved, so I haven't pushed.

**Comment by dmhendricks** [comment]
Why should `composer.lock` be in the repo? 0_o

**Comment by dmhendricks** [comment]
This thing needs a ton of work. My current version has _many_ improvements but time is so limited.

**Comment by dmhendricks** [comment]
On that topic, I'm curious about feedback on something: The dependencies in `composer.json` are meant to be examples, obviously. Carbon Fields is very excellent, but it is not appropriate for every job.

I think that I still want to include it by default because it's a decent example, however, I suppose that I should update the instructions regarding advice/alternatives?

**Comment by dmhendricks** [comment]
In some/several circumstances, it is better to load CF as a [plugin](https://github.com/dmhendricks/carbon-fields-loader). I should probably add that to the docs as well.

**Comment by dmhendricks** [comment]
I'm kind of flip-flopping now on removing the `./vendor` directory. I feel like if someone downloads this it should Just Work™. ???

**Comment by obstschale** [comment]
You left a lot of comments, so let me try to explain myself.

### Composer is a dependency manager ...

... and that said, the goal is to remove the complexity finding and setting up dependencies for a project. You can add all dependencies to your repo, but composer makes it easier. Only state what you want and every developer can use composer to download exactly the required versions of your dependencies and it should work. 

If you add `vendor/` you are doing exactly that, what composer tries to solve. Removing the need of managing dependencies.

(I guess, you know that, but I think it is a good starting point for this comment)

### This is a repository FOR developers

Of course, not everybody knows what composer is but if someone clones this repository s/he should be willing to learn and the docs / readme should point that out.

> In my opinion, the whole point of Composer is managing dependencies. Don't believe me? View source on >25% of the web to determine if they are using WordPress and ask if they know what Composer is.

I think, that argument has some flaws. You are talking about the user who use WordPress, but we are developers and know much more how things work. We know how composer work and we know that in the end the dependencies should end up in a plugin (I come to that). I rather think, WordPress users are like car drivers. They want that the thing works, but the don't need to know how to build it. This is work for an engineer (in our case developer).

### Separate your working place from distribution

I see GitHub as my working place. And composer helps me to keep it clean. If other developers want to work with me or use my stuff from GitHub, they need to know some stuff.

But in the end the plugin will be packed and ready for distribution, for example at wordpress.org. This is a distribution channel where users are. So download a plugin from wordpress.org will always be ready without the need to know composer. All dependencies are within the plugin. So the user can download and install it.

If you want to offer a working version on GitHub, I recommend using git tags (GitHub releases). Firstly, you can manage version and tag them and secondly, GitHub allows you to upload a ZIP or TAR, which will be a working version of that.

### Why should I track `composer.lock`?

There are two things here.

**1. No need for `vendor/` **
You know, when you remove `vendor/` you can easily get it back with a simple `composer install`. And everybody can do this as well. That will keep your repository clean and everybody will have alle dependencies, which are mentioned in `composer.json`.

But there is one drawback: Image you have this line in your `composer.json` file.

    "vendor/package": ">=1.3.2" // anything above or equal to version 1.3.2

This could cause problems. Because if you run `composer install` today you might download version 1.3.2. But if I run this tomorrow I might get version 1.3.4 or even 2.0. This could cause troubles, because the plugin is not tested with a new version of this dependency. Fortunately, there is a simple solution.

**2. Add `composer.lock`**
The `composer.lock` file is generated by composer if you run `composer install`. This file states all dependencies and their exact version downloaded at that time. If that file is in your repository you can be sure anybody running `composer install` will get exactly the dependency versions you used.

**3. This is recommend by composer**
What I just told you is nice but also the recommend way to do. It is mentioned in the composer [docs](https://getcomposer.org/doc/01-basic-usage.md):

>Tip: If you are using git for your project, you probably want to add vendor in your .gitignore. You really don't want to add all of that third-party code to your versioned repository.

>You should commit the composer.lock file to your project repo so that all people working on the project are locked to the same versions of dependencies (more below).

***

I hope this explains it :)
