### ISSUE TITLE
Use WPUpdatePHP to check for PHP Version

### ISSUE THREAD

**Issue by obstschale** [dmhendricks/wordpress-base-plugin#3]
Add PHP Check `wpupdatephp/wp-update-php`.

I like to use [WPupdatePHP](https://github.com/WPupdatePHP/wp-update-php) in my plugins, because I thinks it is good practice to inform the user if their PHP version does not fit my requirements.

Especially useful, when PHP 7 is used in a Plugin.

**Comment by dmhendricks** [comment]
I'm not sure if this is spam, but I dig the idea. I will do it as time is available.

**Comment by dmhendricks** [comment]
I added it, but it's kind of odd. It makes me want to fork it... (If anyone is reading this, please fork it because I don't have the time)

- Terrible: `does_it_meet_required_php_version()` ... You're asking a question in your function name yet echo content rather than only returning a result?
- I want PSR-4

**Comment by dmhendricks** [comment]
Hmm.. This can be accomplished with `phpversion()` and `version_compare()`. I think that I'm going to remove it.

**Comment by obstschale** [comment]
Sure you can use `phpversion()` and `version_compare()`, but I like the simplicity of `WPupdatePHP` because it will not only check for the required version but also will display an admin notice if the requirement does not meet. 

In the end, I don't want to argue about any lib but that idea of informing the user to make it more user friendly :)

**Comment by dmhendricks** [comment]
My current plugin does check and displays a notice, however, I will give WPupdatePHP another look. Thank you.
