### ISSUE TITLE
Path issue on windows

### ISSUE THREAD

**Issue by albertosoho** [dmhendricks/wordpress-base-plugin#6]
When installing on a windows machine, I'm getting this error:

Warning: fopen(C:\Users\admin\Code\CES-Wordpress-Base\wp-content\plugins\CES-Client/CES-Client/CES-Client.php): failed to open stream: No such file or directory in C:\Users\admin\Code\CES-Wordpress-Base\wp-includes\functions.php on line 4835

This folder doesn't exist: 
C:\Users\admin\Code\CES-Wordpress-Base\wp-content\plugins\CES-Client/CES-Client/

Plugin is installed at 
C:\Users\admin\Code\CES-Wordpress-Base\wp-content\plugins\CES-Client/

**Comment by albertosoho** [comment]
$parts = explode( DIRECTORY_SEPARATOR, $key );

That explode isn't working because $key is actually:

string "CES-Client/CES-Client.php"

and DIRECTORY_SEPARATOR equals \

**Comment by dmhendricks** [comment]
Sorry for the late reply. I changed the delimiter to a forward slash. Requires Composer update (if you're updating with Composer from a previous version of the plugin, make sure `dmhendricks/wordpress-toolkit` is version ^0.3.4).

Thank you for reporting!
